"""Criar tabela produto variaçoes

Revision ID: 1cead78788a9
Revises: 569158bb1fe2
Create Date: 2026-06-02 11:16:15.678897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cead78788a9'
down_revision: Union[str, Sequence[str], None] = '569158bb1fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_variacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.String(length=5), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'tamanho', name='uq_produto_tamanho')
    )
    op.create_index(op.f('ix_produto_variacoes_id'), 'produto_variacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_variacoes_id'), table_name='produto_variacoes')
    op.drop_table('produto_variacoes')
    # ### end Alembic commands ###
