"""arrumando o nome de estoque para estoque_atual

Revision ID: 2d7a2ab6e130
Revises: f6312065cd0b
Create Date: 2026-05-26 14:07:59.894493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7a2ab6e130'
down_revision: Union[str, Sequence[str], None] = 'f6312065cd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('estoque_atual', sa.Integer(), nullable=True))
    op.drop_column('produtos', 'estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('estoque', sa.INTEGER(), nullable=True))
    op.drop_column('produtos', 'estoque_atual')
    # ### end Alembic commands ###
