"""Criar tabela produto variaçoes

Revision ID: 523dca1fd6bf
Revises: 331e84bfe6eb
Create Date: 2026-06-02 11:12:11.210296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523dca1fd6bf'
down_revision: Union[str, Sequence[str], None] = '331e84bfe6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
