"""Criar tabela produto variaçoes

Revision ID: 569158bb1fe2
Revises: 523dca1fd6bf
Create Date: 2026-06-02 11:12:40.296974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569158bb1fe2'
down_revision: Union[str, Sequence[str], None] = '523dca1fd6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
